### ISSUE TITLE
[BUG-Error in getting group member list]

### ISSUE THREAD

**Issue by wapchief** [openimsdk/openim-flutter-demo#113]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

Log
```

I/GoLog   (18766): 2024-08-05 10:00:57.938	ERROR	[PID:18766]    	[version:3.8.0]  	[open_im_sdk/caller.go:109]                       	fn call error                                     	{"operationID": "1722852057930", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/group.(*Group).GetGroupMemberList-fm", "cost time": "6 ms", "error": "10002 ArgsError"}
I/F-OpenIMSDK(native call flutter)(18766): method: 【 getGroupMemberList 】, onError: { code:10002, message:10002 ArgsError}
E/flutter (18766): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10002, 10002 ArgsError, null, null)
E/flutter (18766): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (18766): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (18766): <asynchronous suspension>
E/flutter (18766): #2      GroupManager.getGroupMemberList.<anonymous closure> (package:flutter_openim_sdk/src/manager/im_group_manager.dart:95:17)
E/flutter (18766): <asynchronous suspension>
E/flutter (18766): #3      GroupMemberListLogic.onLoad (package:openim/pages/chat/group_setup/group_member_list/group_member_list_logic.dart:113:18)
E/flutter (18766): <asynchronous suspension>
E/flutter (18766): 
```

**Comment by skiffer-git** [comment]
The OIMWS will be phased out, and a new JavaScript SDK is currently under development. This upcoming SDK promises more advanced features and improved performance

**Comment by std-s** [comment]
Hi, using flutter_openim_sdk: ^3.8.1-rc.0.
