### ISSUE TITLE
可以支持一下macos吗？

### ISSUE THREAD

**Issue by lucasjinreal** [openimsdk/openim-flutter-demo#60]
没有任何一个桌面端的支持不太科学啊。代码能跑，但我看是因为bugly和jpush不支持导致：

```
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request
flutter: Error FROM OUT_SIDE FRAMEWORK
flutter: --------------------------------
flutter: Error :  'package:flutter_bugly/src/flutter_bugly.dart': Failed assertion: line 43 pos 7: '(Platform.isAndroid && androidAppId != null) ||
          (Platform.isIOS && iOSAppId != null)': is not true.
flutter: StackTrace :  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      FlutterBugly.init (package:flutter_bugly/src/flutter_bugly.dart:43:7)
#3      Config.init (package:openim_demo/src/common/config.dart:32:18)
<asynchronous suspension>
```

能否在桌面端去掉bugly，如果能支持桌面端，将很大程度的拓展openIM的能力。

**Comment by hrxiang** [comment]
这个后面 会做尝试，请关注官方sdk更新。

**Comment by lucasjinreal** [comment]
@hrxiang 感谢，有一个大概的时间线吗？ 感觉支持起来不难，能跑起来就行，buggly jpush 做一个平台判断就行了。如果有桌面版，我这边就可以做很多测试，效率会高很多，目标用户也比较需要桌面版
