### ISSUE TITLE
flutter: Error FROM OUT_SIDE FRAMEWORK flutter: -------------------------------- flutter: Error :  'package:flutter_bugly/src/flutter_bugly.dart': Failed assertion: line 43 pos 7: '(Platform.isAndroid && androidAppId != null) ||           (Platform.isIOS && iOSAppId != null)': is not true. flutter: StackTrace :  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61) #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5) #2      FlutterBugly.init (package:flutter_bugly/src/flutter_bugly.dart:43:7) #3      Config.init (package:openim_demo/src/common/config.dart:32:18) <asynchronous suspension>  Error connecting to the service protocol: failed to connect to http://127.0.0.1:65513/pPwpNt-choU=/ flutter: | JPUSH | Flutter | addEventHandler: flutter: | JPUSH | Flutter | setup: flutter: | JPUSH | Flutter | applyPushAuthority: flutter: | JPUSH | Flutter | getRegistrationID:

### ISSUE THREAD

**Issue by lucasjinreal** [openimsdk/openim-flutter-demo#63]
flutter: Error FROM OUT_SIDE FRAMEWORK
flutter: --------------------------------
flutter: Error :  'package:flutter_bugly/src/flutter_bugly.dart': Failed assertion: line 43 pos 7: '(Platform.isAndroid && androidAppId != null) ||
          (Platform.isIOS && iOSAppId != null)': is not true.
flutter: StackTrace :  #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      FlutterBugly.init (package:flutter_bugly/src/flutter_bugly.dart:43:7)
#3      Config.init (package:openim_demo/src/common/config.dart:32:18)
<asynchronous suspension>

Error connecting to the service protocol: failed to connect to http://127.0.0.1:65513/pPwpNt-choU=/
flutter: | JPUSH | Flutter | addEventHandler:
flutter: | JPUSH | Flutter | setup:
flutter: | JPUSH | Flutter | applyPushAuthority:
flutter: | JPUSH | Flutter | getRegistrationID:

**Comment by lucasjinreal** [comment]
Please make desktop support!!!!!!

**Comment by lucasjinreal** [comment]
@hrxiang 支持一下桌面端可以吗？
